/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_n1ar4_gate_loader_CRTLoader */

#ifndef _Included_me_n1ar4_gate_loader_CRTLoader
#define _Included_me_n1ar4_gate_loader_CRTLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_n1ar4_gate_loader_CRTLoader
 * Method:    exec0
 * Signature: ([BILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_me_n1ar4_gate_loader_CRTLoader_exec0
        (JNIEnv *, jobject, jbyteArray, jint, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
