/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_n1ar4_gate_loader_DivideLoader */

#ifndef _Included_me_n1ar4_gate_loader_DivideLoader
#define _Included_me_n1ar4_gate_loader_DivideLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_n1ar4_gate_loader_DivideLoader
 * Method:    exec0
 * Signature: ([BIZ)V
 */
JNIEXPORT void JNICALL Java_me_n1ar4_gate_loader_DivideLoader_exec0
        (JNIEnv *, jobject, jbyteArray, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
