/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_n1ar4_gate_core_TartarusGate */

#ifndef _Included_me_n1ar4_gate_core_TartarusGate
#define _Included_me_n1ar4_gate_core_TartarusGate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_n1ar4_gate_core_TartarusGate
 * Method:    exec0
 * Signature: ([BIZ)V
 */
JNIEXPORT void JNICALL Java_me_n1ar4_gate_core_TartarusGate_exec0
(JNIEnv *, jobject, jbyteArray, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
